### ISSUE TITLE
TYPO in “ppl.pmx/docs/operators/dynamic_batching/MultiHeadAttention.md”

### ISSUE THREAD

**Issue by wplf** [openppl-public/ppl.pmx#10]
Is the 'togather' supposed to be 'together' in “ppl.pmx/docs/operators/dynamic_batching/MultiHeadAttention.md” ?
> Because dynamic batching will combine decoding attention and first-fill attention togather, we have to pass some information to separate input into two part by decoding_batches.

**Comment by Alcanderian** [comment]
Yes, it is. Thanks for pointing out the typo

**Comment by Alcanderian** [comment]
#12
