### ISSUE TITLE
怎么转换其它模型

### ISSUE THREAD

**Issue by maiquanshen** [openppl-public/ppl.pmx#15]
你好，请问怎么转换其它模型，比如bloom，whisper。
是参考llama的几个转换命令吗？
另外请教一下模型的parame.json怎么获取得到呢，我看在hf上下载的模型里面都没有这个文件。

**Comment by Alcanderian** [comment]
bloom，whisper目前还没有官方model zoo支持，如果需要转模型需要先自己用pmx算子构建模型，再进行导出，或者等待我们官方的model zoo进行相应的模型支持。param.json每个模型会有少许不一样，hf上可能是config.json

**Comment by maiquanshen** [comment]
> bloom，whisper目前还没有官方model zoo支持，如果需要转模型需要先自己用pmx算子构建模型，再进行导出，或者等待我们官方的model zoo进行相应的模型支持。param.json每个模型会有少许不一样，hf上可能是config.json

我看大部分的模型都没有tokenizer.pth文件，更多的是tokenizer.json  你们的pmx算子构建模型时支持这个json文件输入的吗？

**Comment by Alcanderian** [comment]
> > bloom，whisper目前还没有官方model zoo支持，如果需要转模型需要先自己用pmx算子构建模型，再进行导出，或者等待我们官方的model zoo进行相应的模型支持。param.json每个模型会有少许不一样，hf上可能是config.json
> 
> 我看大部分的模型都没有tokenizer.pth文件，更多的是tokenizer.json 你们的pmx算子构建模型时支持这个json文件输入的吗？

目前PMX偏向于类似hf的单模型单文件夹支持，一般模型都会有tokenizer.model，目前主要支持这种输入，json可以按各个模型的需求进行相应的调整
