### ISSUE TITLE
文档内显示支持qwen1.5，但实际转换报错。

### ISSUE THREAD

**Issue by poemon1** [openppl-public/ppl.pmx#77]
使用的model_zoo/qwen/huggingface/ConvertWeightToOpmx.py，py文件内param参数全都是对应qwen而非qwen1.5设置的。无法找到qwen1.5权重转换对应的脚本。

**Comment by Alcanderian** [comment]
你好，qwen1.5可以直接使用llama的转换脚本（但是不支持sliding window），这里是写文档的时候出问题了，后续会更正
